baseURL = "https://ffreshman.github.io/"
languageCode = "zh-hans"
title = "小咸鱼的博客"
theme = "dream"
backgroundImage = "/img/cover.png"
github = "FFreshman"
disqusShortname = "..."
avatar = "/img/cover.png"
author = "FFreshman"
motto = "兴趣是最好的老师！"