baseURL = "https://ffreshman.github.io/"
languageCode = "zh-hans"
title = "小咸鱼的博客"
theme = "dream"

# disqusShortname = ""
[params]
    avatar = "/img/22.png"
    author = "FFreshman"
    motto = "兴趣是最好的老师！"
    backgroundImage = "/img/cover.png"
    siteStartYear = 2019
    github = "FFreshman"
    email = "1366157248@qq.com"

    # dark mode
    darkLinkColor = "darkseagreen"
    dark404Button = true

    
#这是html是否保留部分
[markup.goldmark.renderer]
unsafe= true